/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'serviceName' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'problemDescription' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'submitServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'serviceName' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'problemDescription' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'submitServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };